print('|-----------------------------|')
print('|\t OFITSIANT BLAKNOTI   |')
print('|-----------------------------|')
stol = int(input('\t stol raqami: '))
print('|-----------------------------|')
choy = int(input(f'\t choy soni: '))
print('|-----------------------------|')
non = int(input('\t non soni: '))
print('|-----------------------------|')
salat = int(input('\t salat soni: '))
print('|-----------------------------|')
taom_1 = str(input('\t 1-taom nomi: '))
print('|-----------------------------|')
taom_2 = str(input('\t 2-taom nomi: '))
print('|-----------------------------|')
print('|-----------------------------|')
taom_soni1 = str(input('\t 1-taom soni: '))
print('|-----------------------------|')
taom_soni2 = str(input('\t 2-taom soni: '))           #Restoran uchun elektron menyu
print('|-----------------------------|')
print('\n\n\n')
print('|-----------------------------|')
print(f'| {stol} - STOL!\t\t    |')
print('|-----------------------------|')
print(f'| choy {choy} ta - 1500 so\'mdan\t\t |')
print('|-----------------------------|')
print(f'| non {non} ta - 3000 so\'mdan\t\t |')
print('|-----------------------------|')
print(f'| salat {salat} ta - 2000 so\'mdan\t\t |')
print('|-----------------------------|')
print(f'| 1-taom {taom_1} {taom_soni1} ta \t\t |')
print('|-----------------------------|')
print(f'| 2-taom {taom_2} {taom_soni2} ta \t\t |')