a = int(input("sonni kiriting "))
b = int(input("sonni kiriting "))
c = int(input("sonni kiriting "))
hona1 = (a//2) + (a%2)
hona2 = (b//2) + (b%2)                           # 71-bet 9-mashq
hona3 = (c//2) + (c%2)
print(f'1-xonaga {hona1} ta parta kerak' )
print(f'2-xonaga {hona2} ta parta kerak' )
print(f'3-xonaga {hona3} ta parta kerak' )
print(f'jami {hona1+hona2+hona3} ta parta kerak' )
